# Generated by Django 2.2 on 2019-04-13 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_number', models.CharField(max_length=16)),
                ('building_year', models.IntegerField()),
                ('developer', models.CharField(max_length=256)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('score_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiration_date', models.DateTimeField()),
                ('building', models.ManyToManyField(to='hackathon.Building')),
                ('property_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.PropertyGroup')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('bsn_number', models.IntegerField()),
                ('buildings', models.ManyToManyField(to='hackathon.Building')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingMutator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
                ('property_groups', models.ManyToManyField(to='hackathon.PropertyGroup')),
            ],
        ),
    ]
